add_executable(test_simple_examples test_simple_examples.c)
target_compile_definitions(test_simple_examples PRIVATE
	SIMPLE_EXAMPLES_DIR="${PROJECT_SOURCE_DIR}/data/simple_examples"
)
target_link_libraries(test_simple_examples PRIVATE lp_simplex)
add_test(NAME test_simple_examples COMMAND test_simple_examples)
